name = "FilesTreeTools"
uuid = "638332cd-b357-4bf5-bfa2-3531168477f5"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.3.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
